title: "IDR OME-NGFF Samples"
description: "A collection of OME-NGFF filesets converted from IDR data"
author: "OME"

remote_theme: "jekyll/minima@master"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap
