title: "IDR OME-NGFF Samples"
description: "A collection of OME-NGFF filesets converted from IDR data"
author: "OME"

theme: minima
baseurl: "/ome-ngff-samples"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

exclude:
  - .pixi/
  - pixi.toml
  - pixi.lock

sass:
  quiet_deps: true
